name: Build MAUI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI workloads
        run: dotnet workload install maui

      - name: Restore
        run: dotnet restore "Student_Onboarding_Backend/Student_Onboarding_Backend/Student Onboarding Platform.sln"

      - name: Build
        run: dotnet build "Student_Onboarding_Backend/Student_Onboarding_Backend/Student Onboarding Platform.sln" --configuration Release --no-restore
